### Obtener todos los usuarios
GET http://localhost:3000/api/usuarios
Content-Type: application/json

### Registrar nuevo usuario
POST http://localhost:3000/api/usuarios/registro
Content-Type: application/json

{
  "id": 21,
  "username": "Zoe",
  "email": "zoe@example.com",
  "password": "claveZoe123"
}

POST http://localhost:3000/api/usuarios/login
Content-Type: application/json

{
  "email": "zoe@example.com",
  "password": "claveZoe123"
}
